# Generated by Django 6.0.4 on 2026-04-12 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Praga/Doença')),
                ('descricao', models.TextField(verbose_name='Descrição Técnica')),
                ('recomendacao_manejo', models.TextField(help_text='O que o produtor deve fazer ao identificar este problema.', verbose_name='Recomendação de Manejo (Embrapa)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: Em qual parte da planta está o problema?', max_length=255, verbose_name='Texto da Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: Na folha', max_length=200, verbose_name='Texto da Opção')),
                ('diagnostico_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostico.diagnostico', verbose_name='Diagnóstico Final (Se encerrar a triagem)')),
                ('pergunta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='diagnostico.pergunta', verbose_name='Pergunta de Origem')),
                ('proxima_pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcoes_que_trazem_aqui', to='diagnostico.pergunta', verbose_name='Próxima Pergunta (Se houver)')),
            ],
        ),
    ]
