# Generated by Django 6.0.4 on 2026-04-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Identificador único do ESP32 (ex: ceres_001).', max_length=50, verbose_name='ID do Dispositivo')),
                ('classe_detectada', models.CharField(blank=True, help_text='Nome da doença detectada pelo modelo TFLite.', max_length=100, null=True, verbose_name='Classe Detectada')),
                ('confianca', models.FloatField(blank=True, help_text='Probabilidade retornada pelo modelo (0.0 a 1.0).', null=True, verbose_name='Confiança (%)')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('umidade_ar', models.IntegerField(verbose_name='Umidade do Ar (%)')),
                ('umidade_solo', models.IntegerField(verbose_name='Umidade do Solo (%)')),
                ('timestamp', models.DateTimeField(help_text='Momento da captura no ESP32 (ISO8601).', verbose_name='Timestamp do Dispositivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='diagnostico.diagnostico', verbose_name='Diagnóstico Associado')),
            ],
            options={
                'verbose_name': 'Evento de Diagnóstico',
                'verbose_name_plural': 'Eventos de Diagnóstico',
                'ordering': ['-criado_em'],
            },
        ),
    ]
