# Generated by Django 6.0.4 on 2026-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_diagnosticoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoevento',
            name='temperatura',
            field=models.FloatField(blank=True, help_text='Leitura do sensor DHT22. Nulo se sensor não conectado.', null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='diagnosticoevento',
            name='umidade_ar',
            field=models.FloatField(blank=True, help_text='Leitura do sensor DHT22. Nulo se sensor não conectado.', null=True, verbose_name='Umidade do Ar (%)'),
        ),
        migrations.AlterField(
            model_name='diagnosticoevento',
            name='umidade_solo',
            field=models.FloatField(blank=True, help_text='Leitura do sensor capacitivo. Nulo se sensor não conectado.', null=True, verbose_name='Umidade do Solo (%)'),
        ),
    ]
