# Generated by Django 6.0.4 on 2026-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_sensor_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoevento',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordenada GPS capturada pelo celular no momento do diagnóstico.', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='diagnosticoevento',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordenada GPS capturada pelo celular no momento do diagnóstico.', null=True, verbose_name='Longitude'),
        ),
    ]
